import os
import sys
import asyncio
import traceback
import tempfile
import streamlit as st
from core.graph import build_graph
from core.state import ReleaseState

if sys.platform == "win32" and hasattr(asyncio, "WindowsSelectorEventLoopPolicy"):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

st.set_page_config(page_title="Release Validation AI", layout="wide")

st.title("Release Validation AI Agent")
st.markdown("Validate Release Notes PDFs for structural correctness, dates, versions, and linked file paths.")

upload_mode = st.radio("Choose Input Method:", ["File Upload", "Network/Local Path"])

pdf_path = None
if upload_mode == "File Upload":
    uploaded_file = st.file_uploader("Upload the Release PDF", type=["pdf"])
else:
    pdf_path_input = st.text_input("Enter the path to the Release PDF (local or network path):")

if st.button("Run Validation"):
    if upload_mode == "File Upload":
        if uploaded_file is not None:
            # Save uploaded file to a temporary file
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                tmp_file.write(uploaded_file.getvalue())
                pdf_path = tmp_file.name
        else:
            st.error("Please upload a PDF file.")
    else:
        if not pdf_path_input:
            st.error("Please provide a path to a PDF file.")
        else:
            # Strip trailing/leading spaces or quotes from drag-and-drops
            pdf_path = pdf_path_input.strip().strip('\"\'').strip()
            
            # Autocorrect missing double slashes for UNC paths if user copied "\162.70..." instead of "\\162.70..."
            if pdf_path.startswith("\\") and not pdf_path.startswith("\\\\"):
                potential_path = "\\" + pdf_path
                if os.path.exists(potential_path):
                    pdf_path = potential_path
            
            if not os.path.exists(pdf_path):
                st.error(f"Error: Could not find file at `{pdf_path}`. If this is a deployed app, the server cannot access your local or network paths. Please use 'File Upload' instead.")
                pdf_path = None

    if pdf_path is not None:
        try:
            graph = build_graph()
            initial_state = ReleaseState(pdf_path=pdf_path)
            
            with st.status("Running Release Validation Pipeline...", expanded=True) as status:
                st.write("Initializing...")
                
                result = None
                # Stream the graph execution to show real-time progress
                for step_output in graph.stream(initial_state):
                    for node_name, node_state in step_output.items():
                        step_names = {
                            "extract_pdf": "Extracted PDF text",
                            "extract_links": "Extracted PDF links",
                            "resolve_paths": "Resolved file paths",
                            "validate_pdfs": "Validated linked PDFs",
                            "validate_toc": "Validated table of contents",
                            "generate_report": "Generated AI Report"
                        }
                        st.write(f" {step_names.get(node_name, node_name)}")
                        
                        if node_name == "generate_report":
                            result = node_state
                
                status.update(label="Validation Complete!", state="complete", expanded=False)

            st.subheader("Final Report")
            final_report = result.get("final_report", "").strip() if result else ""

            if final_report:
                st.markdown(final_report)
            else:
                st.warning("No report content was generated by the AI agent.")

        except Exception as e:
            st.error(f"An error occurred during validation: {str(e)}")
            st.code(traceback.format_exc(), language="python")